#Code for dockerfile taken from <https://docs.docker.com/engine/examples/running_ssh_service/>
#This file has passwords specified for learning purpose. Please change these while using before proceeding.
FROM ubuntu

ARG ssh_user_password

ARG ROOT_PASSWORD

RUN echo $ssh_user_password

RUN useradd ssh_user && \
    echo "ssh_user:${ssh_user_password}" | chpasswd

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:${ROOT_PASSWORD}' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

