#Variables specified in env_file will be visible in the container, So this file can be used as config file for an application 
version: '3'
services:
    node_service:
        image: node_custom_image
        build: 
            context: .
        container_name: node_container
        tty: true
        ports: 
            - 3001:8000
        env_file: ./env_sample
