version: '3'
services:
    ubuntu_service:
        image: node_custom_image
        build: 
            context: "https://github.com/kathuriaas/docker_example.git"
        container_name: node_container
        tty: true
        ports: 
            - 8000:8000
