# Here one volume is used as path, so location should be writable by jenkins
# Variable is this file (e.g. ssh_user_password and ROOT_PASSWORD) are substituted from shell's env variables OR .env file. and are just scoped at shell of host.
# For environment variables to be used in build/container, use ARGS/ENV.
# See <https://docs.docker.com/compose/compose-file/#variable-substitution> for details.
version: '3'
services:
    jenkins_service:
        image: jenkins/jenkins
        container_name: jenkins_container
        restart: always
        volumes:
            - jenkins_home:/var/jenkins_home
            - $HOME/jenkins_files:/tmp/jenkins_files
        ports: 
            - 8080:8080
            - 50000:50000
        networks: 
            - network1
    ssh_server:
        image: ubuntu_ssh_server
        container_name: ubuntu_container
        build:
            context: ./ssh_server
            args: 
                - ssh_user_password=${ssh_user_password}
                - ROOT_PASSWORD=${ROOT_PASSWORD}
        restart: always
        tty: true
        networks: 
            - network1
networks: 
    network1:
volumes: 
    jenkins_home: