#Before deploying, add .env file at same level of docker-compose.yml OR add shell env variable for PGSQL_PASSWORD, to be used, when DB is created first time. 
version: '3'
services:
    postgres_service:
        image: postgres
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes: 
    postgres_data:
